### ISSUE TITLE
Output Spaces "asl" Bug

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#111]
I was submitting an ASLPREP job (version 0.2.6, using a singularity image) and specifying some additional "--output-spaces". The  readthedocs page says "asl" should be a valid output space, but when submitted I got this error:

ValueError: space identifier "asl" is invalid.
Valid identifiers are: MNI152Lin, MNI152NLin2009cAsym, MNI152NLin2009cSym, MNI152NLin6Asym, MNI152NLin6Sym, MNIInfant, MNIPediatricAsym, NKI, OASIS30ANTs, PNC, WHS, fsLR, fsaverage, T1w, T2w, anat, fsnative, func, run, sbref, session

Re-running with "func" instead of "asl" seems to be working fine so this is a very minor problem, just writing this in case someone else runs into the same issue.

**Comment by a3sha2** [comment]
thank you  @caugolm 

this has been take care of.
can you try this new image that include PASL `pennlinc/aslprep:0.2.6pasl`

**Comment by caugolm** [comment]
Hi Azeez, thanks for working on this so quickly! Unfortunately, I'm getting a new error I can't figure out:

Job was executed on host(s) <8*ftdc-gpu01>, in queue <ftdc_normal>, as user <olm> in cluster <PMACS-SCC> at Tue Jan 19 13:30:25 2021
</home/olm> was used as the home directory.
</project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/scripts> was used as the working directory.
Started at Tue Jan 19 13:30:25 2021
Terminated at Tue Jan 19 13:31:13 2021
Results reported at Tue Jan 19 13:31:13 2021

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
singularity run -e -B /project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/:/project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep/,/home/olm/.cache/templateflow:/templateflow /project/ftdc_pipeline/aslprep/aslprep-0.2.6pasl_20210119.simg /project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep//bids2 /project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep//aslprepout participant --participant_label test001 --nprocs 8 --mem 30GB -w /project/ftdc_volumetric/MultiCenter/LEFFTDS/aslprep//wrkdir --skip_bids_validation --basil --scorescrub --output-spaces T1w func fsaverage MNI152NLin2009cAsym --sloppy
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   24.00 sec.
    Max Memory :                                 329 MB
    Average Memory :                             29.80 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              7
    Max Threads :                                15
    Run time :                                   48 sec.
    Turnaround time :                            49 sec.

The output (if any) follows:

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-bgquw9y5 because the default path (/home/aslprep/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/cli/workflow.py", line 20, in build_workflow
    from ..workflows.base import init_aslprep_wf
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/workflows/base.py", line 20, in <module>
    from ..interfaces import SubjectSummary, AboutSummary, DerivativesDataSink
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/interfaces/__init__.py", line 5, in <module>
    from ..niworkflows.interfaces import (
  File "/usr/local/miniconda/lib/python3.7/site-packages/aslprep/niworkflows/interfaces/freesurfer.py", line 10, in <module>
    from skimage import morphology as sim
  File "/usr/local/miniconda/lib/python3.7/site-packages/skimage/__init__.py", line 121, in <module>
    from ._shared import geometry
  File "skimage/_shared/geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
