### ISSUE TITLE
root permissions for output files & threads

### ISSUE THREAD

**Issue by geowk** [PennLINC/aslprep#146]
Hello,

Just started using aslprep using a docker container. Had some experience using fmri-prep, so that helped when first attempting to use aslprep successfully.

A few questions:

1). Output directories and files all have root owner and group permissions despite starting aslprep docker container under my own username and group (or any other user for that matter). This becomes a problem when  trying to remove files no longer needed or editing files. When using fmriprep, there was an option: -u $(id -u):$(id -g), one could add to the command line that would preserve user and group permissions for the output files/directories. Does something similar exist for aslprep?

2). What is the difference between --nprocs/--nthreads options vs --omp-nthreads option? The help states and "all vs per process" difference, but wasn't sure exactly what that meant.

3). How much memory does a typical  aslprep process consume? What is the maximum amount memory used if one chooses the --low-mem option?

Thanks.

g.

**Comment by a3sha2** [comment]
Hi @geowk 

1. Yes, you can bind the docker image just like fmriprep, it works in the same way 
2. nprocs, and nthreads are the same. that is maximum number of threads across all processes but omp-nthreads  is maximum number of threads per-process see https://aslprep.readthedocs.io/en/latest/usage.html#Options%20to%20handle%20performance
3. it depend one the size of the data, I will recommended 8GB  or more with low-mem. option

**Comment by geowk** [comment]
> 

Hi a3sha2. Thanks for the reply.

I'm still confused by your reply #1.

I tried running the following command. This time I added the option:

 -u $(id -u):$(id -g) to the command line like I would for fmriprep. The goal is to have the output files to have my username as owner and belonging to my primary group and not the root as owner and primary group.

Running this:

`docker run -ti --rm -v /study/rawdata/:/data/:ro -v /study/rawdata/derivatives/:/out  -v /study/rawdata/derivatives/aslprep/work:/work -v $FREESURFER_HOME:/fs pennlinc/aslprep /data/ /out/aslprep participant  --participant-label 'sub-001' -u $(id -u):$(id -g)  --fs-license-file /fs/license.txt --nprocs 10 --mem 10 -w /work`

I get the following error message:

aslprep: error: unrecognized arguments: -u 1000:1001

What is the appropriate option use in aslprep?

Thanks.

g.

**Comment by pcamach2** [comment]
Hi @geowk,

The error means that the -u argument added does not correspond to a variable or option to set for aslprep.

The function of that argument in the docker wrapper for fmriprep was to run the container as a user or userID:groupID. Note that here you are calling a docker run directly, not through a shell wrapper.

You should be able to run the container as your user by placing this argument in the docker run command before you specify the image pennlinc/aslprep as follows:

`docker run -ti --rm -u $(id -u):$(id -g) -v /study/rawdata/:/data/:ro -v /study/rawdata/derivatives/:/out -v /study/rawdata/derivatives/aslprep/work:/work -v $FREESURFER_HOME:/fs pennlinc/aslprep /data/ /out/aslprep participant --participant-label 'sub-001' --fs-license-file /fs/license.txt --nprocs 10 --mem 10 -w /work`

Hope this helps!

Cheers

**Comment by geowk** [comment]
Hello,

I've recently revisited this issue. Thank you for your suggestion and sorry for the delay in response.

`docker run -ti --rm -u $(id -u):$(id -g) -v /study/rawdata/:/data/:ro -v /study/rawdata/derivatives/:/out -v /study/rawdata/derivatives/aslprep/work:/work -v $FREESURFER_HOME:/fs pennlinc/aslprep /data/ /out/aslprep participant --participant-label 'sub-001' --fs-license-file /fs/license.txt --nprocs 10 --mem 10 -w /work`

I still get a permission error with the above code

`PermissionError: [Errno 13] Permission denied: '/work/bids.db`

If I exclude the option `-w /work`

I get this message

`PermissionError: [Errno 13] Permission denied:  'out/aslprep/aslprep'`

I think the changes makes me a user, but still prevents me from writing/creating/editing file/folder created by the docker container since the created output files are still root owner and root group.

-g

**Comment by geowk** [comment]
Okay, I had to make the work and data directories prior to running the docker run command. Now my output directories and results have the my username and group instead of root and root as owner and group.

Thanks again.

g
