### ISSUE TITLE
'No "moz" images found' although present in BIDS directory

### ISSUE THREAD

**Issue by felenae** [PennLINC/aslprep#175]
Dear Azeez,

I receive the following INFO messages when running aslprep-2.0.7 on 3D PCASL data using singularity on a Centos 7 HPC:

```
211208-12:57:06,788 nipype.workflow INFO:
	 [Node] Setting-up "aslprep_wf.single_subject_<>_wf.bidssrc" in "/tmp/aslprep_wf/single_subject_<>_wf/bidssrc".
211208-12:57:06,792 nipype.workflow INFO:
	 [Node] Running "bidssrc" ("aslprep.niworkflows.interfaces.bids.BIDSDataGrabber")
211208-12:57:06,796 nipype.interface INFO:
	 No "fmap" images found for sub-<>
211208-12:57:06,797 nipype.interface INFO:
	 No "sbref" images found for sub-<>
211208-12:57:06,797 nipype.interface INFO:
	 No "roi" images found for sub-<>
211208-12:57:06,798 nipype.interface INFO:
	 No "m0z" images found for sub-<>
211208-12:57:06,798 nipype.interface INFO:
	 No "cbf" images found for sub-<>
211208-12:57:06,803 nipype.workflow INFO:
	 [Node] Finished "aslprep_wf.single_subject_<>_wf.bidssrc".
```
#### aslprep call
```
singularity run --cleanenv --userns \
    -B $PROJ_DIR \
    -B $(readlink -f $ENV_DIR) \
    -B $TMP_DIR/:/tmp \
    -B $TMP_IN:/tmp_in \
    -B $TMP_OUT:/tmp_out \
    $ENV_DIR/$container_aslprep \
         /tmp_in /tmp_out participant \
         --participant-label $1 \
         --work-dir /tmp \
         --fs-license-file envs/freesurfer_license.txt \
         --skip-bids-validation \
         --nthreads $SLURM_CPUS_PER_TASK \
         --omp-nthreads $OMP_NTHREADS \
         --mem_mb $MEM_MB \
         --ignore fieldmaps slicetiming sbref \
         --output-spaces asl T1w MNI152NLin2009cAsym \
         --asl2t1w-init register \
         --asl2t1w-dof 6 \
         --force-bbr
         --use-syn-sdc
         --force-syn
         --m0_scale 10 \
         --scorescrub \
         --basil \
         --skull-strip-template OASIS30ANTs \
         --skull-strip-fixed-seed \
         --random-seed 42 \
         --skull-strip-t1w force \
         --notrack \
         --verbose"
```

I am surprised by this information, as `sub-<>_ses-1_m0scan.nii.gz/sub-<>_ses-1_m0scan.json files` are present, the latter including the field `"IntendedFor": "ses-1/perf/sub-<>_ses-1_asl.nii.gz"`. 

I wonder whether this impacts the CBF computations? However, from what I can tell by now, the CBF output seems reasonable.

I would appreciate your point of view!

Thanks and all the best,
Felix

**Comment by a3sha2** [comment]
yes , it will have impact

**Comment by felenae** [comment]
What is strange though, is that I **do not** get this error:

https://github.com/PennLINC/aslprep/blob/4b07ea9f6e8e2b3ed2d47bf3579ee65aae64631d/aslprep/interfaces/cbf_computation.py#L118

In an earlier (closed) issue (https://github.com/PennLINC/aslprep/issues/61#issuecomment-686544876) you were explaining that aslprep looks for m0scan as follows: 

> aslprep will first check if moscan (`_**moscan.nii.gz'**) is available for a particular asl data

However from what I see in the code, it looks like the naming convention is indeed, as suggested by BIDS, **m0scan.nii.gz**:

https://github.com/PennLINC/aslprep/blob/4b07ea9f6e8e2b3ed2d47bf3579ee65aae64631d/aslprep/interfaces/cbf_computation.py#L114

So I am suspecting that the info I've got ("211208-12:57:06,798 nipype.interface INFO: No "m0z" images found for sub-<>"), is a remnant of the bids query expecting a _moscan.nii.gz instead of a _m0scan.nii.gz, while the actual cbf computation works just fine.

**Comment by a3sha2** [comment]
yes, you are right, the error is from pyBIDS, I will  submit issues to them

**Comment by tsalo** [comment]
AFAICT, ASLPrep doesn't use loaded m0scan or deltam images, even if it collects them.
