### ISSUE TITLE
Freesurfer reconstruction did not run

### ISSUE THREAD

**Issue by dkp** [PennLINC/aslprep#177]
I've used fMRIprep and QSIprep with my freesurfer license (license.txt in my home directory).  I'm probably missing something, but freesurfer did not run when I tried ASLprep on inputs/ds000240/sub-01
-------------
ASLprep completed in one hour with no errors using the following command (but there was no freesurfer processing)

docker run -ti -m 30GB --rm -v $HOME/license.txt:/license/license.txt -v ${PWD}/inputs/ds000240:/data:ro -v ${PWD}/outputs/derivatives:/out:rw -v ${PWD}/work:/work:rw pennlinc/aslprep /data /out participant --participant-label 01 --fs-license-file /license/license.txt -w /work

I'm attaching the log file.
[aslprep.txt](https://github.com/PennLINC/aslprep/files/7811823/aslprep.txt)

Any insights are appreciated!  Thank you.

-Dianne

**Comment by a3sha2** [comment]
@dkp 

yes, freesurfer was suppressed but we still use some other freesurfer  commands

**Comment by a3sha2** [comment]
we may add freesurfer later on for cifti

**Comment by dkp** [comment]
Thanks!  It certainly runs faster for testing without freesurfer!  I'm glad I'm not just doing something wrong.

-Dianne
