### ISSUE TITLE
aslprep error, HCP-PCASL sequence (multi-PLD, M0=included)

### ISSUE THREAD

**Issue by markushs** [PennLINC/aslprep#183]
Hi,

As mentioned here https://github.com/PennLINC/aslprep/issues/178#issuecomment-1056910047, I am trying to run some data collected with the HCP-PCASL sequence through aslprep. 

The `*_asl.nii.gz` consists of 43 tag-control pairs (with PLDs varying between 0.2 and 2.2 seconds) and two M0-images. Total number of frames in the asl-volume it thus 88, the last two frames being M0s. This is reflected in the `*_aslcontext.tsv`.

Here's a screenshot of the script I use to set up the relevant BIDS-parameters: 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/44242647/156571472-6086b801-207c-4e1f-915b-946b2e2a7dce.png">

Not completely sure about the `RepetitionTimePreparation`-parameter, which is required by the bids-validator, but I cannot see that this parameter is used anywhere in aslprep so I guess the specific value doesn't matter.

ASLprep fails after a few seconds with this error. 

<img width="2015" alt="image" src="https://user-images.githubusercontent.com/44242647/156569892-9e951879-5591-4c9c-9789-c5ed4fdd8a39.png">

Thanks again!

**Comment by tsalo** [comment]
It looks like this is the same problem as #196, which should be fixed in #222. Unfortunately, the way multi-PLD data are averaged in ASLPrep was apparently wrong, so I've had to disable multi-PLD processing for the 0.3.0 release. I will hopefully have it up and running by the next release.
