### ISSUE TITLE
path does not exist for --anat-derivatives

### ISSUE THREAD

**Issue by Loowie** [PennLINC/aslprep#184]
Dear aslprep team

I just started trying out aslprep for our ASL-data. Wonderful work you did! It also works with our test dataset. We plan on doing both fmriprep and aslprep since we have both BOLD-images and ASL-images from the same subject during the same session. For this reason, I wanted to use the --anat-derivatives flag so ASLprep would use the already preprocessed T1 images from fmriprep, but it gives me an error saying that the --anat-derivatives path does not exist (aslprep: error: Path does not exist) although the derivatives\sub-xxxx\anat map really exists...

What could be going wrong here? Thanks for any advice!

I put up an example test dataset on my computer at GBW_MyDownloads under asl_test_fmriprep. Here's the code I use to run it:
docker run -ti -m 12GB --rm -v C:\GBW_MyDownloads\freesurfer_license.txt:/license/license.txt -v C:\GBW_MyDownloads\asl_test_fmriprep:/data:ro  -v C:\GBW_MyDownloads\asl_test_fmriprep\derivatives:/out:rw -v C:\GBW_MyDownloads\asl_test_fmriprep\work:/work:rw pennlinc/aslprep:latest /data /out participant  --participant-label 9999 --fs-license-file /license/license.txt -w /work --anat-derivatives C:\GBW_MyDownloads\asl_test_fmriprep\derivatives\sub-9999\anat

**Comment by tsalo** [comment]
@Loowie I'm sorry for the delay. It looks like you need to mount your anatomical derivatives and point to that path instead. Also, I think you need to point to the anatomical derivatives location, rather than the individual subject's subfolder in that derivatives folder.

```diff
docker run -ti -m 12GB --rm \
    -v C:\GBW_MyDownloads\freesurfer_license.txt:/license/license.txt \
    -v C:\GBW_MyDownloads\asl_test_fmriprep:/data:ro \
    -v C:\GBW_MyDownloads\asl_test_fmriprep\derivatives:/out:rw \
    -v C:\GBW_MyDownloads\asl_test_fmriprep\work:/work:rw \
+  -v C:\GBW_MyDownloads\asl_test_fmriprep\derivatives:/anat-derivatives \
    pennlinc/aslprep:latest /data /out participant --participant-label 9999 \
    --fs-license-file /license/license.txt \
    -w /work \
-   --anat-derivatives C:\GBW_MyDownloads\asl_test_fmriprep\derivatives\sub-9999\anat
+   --anat-derivatives /anat-derivatives
```
