### ISSUE TITLE
What is the origin of the non-BIDS "DELTAM" and "MoScan" suffixes and "asl" datatype?

### ISSUE THREAD

**Issue by tsalo** [PennLINC/aslprep#214]
The pybids config files in this repository reference an "asl" datatype, a "DELTAM" suffix, and a "MoScan" suffix. None of these exist in BIDS. I'm wondering where they came from and why they were added to aslprep.

**Comment by cookpa** [comment]
I was talking to @caugolm about this recently. I think these options predated the adoption of the ASL BIDS extension almost precisely two years ago.

**Comment by tsalo** [comment]
Thanks @cookpa! In that case, I will remove them.

**Comment by cookpa** [comment]
@caugolm any thoughts on this? I know we have a lot of ASL data curated the unofficial way.

**Comment by caugolm** [comment]
It makes sense to me for ASLPrep to only consider "official" BIDS and remove these early guesses/workarounds. Any legacy data we have curated has bids (or bids-ish) file names, but without the additional necessary fields in the jsons, so when we re-curate it's just as well to have to do all of it correctly.
