### ISSUE TITLE
ModuleNotFoundError: No module named 'aslprep.smriprep'

### ISSUE THREAD

**Issue by philjohnston** [PennLINC/aslprep#228]
I'm attempting to use the current unstable version (pulled 2023.03.01, following this discussion: https://github.com/PennLINC/aslprep/issues/196). It runs for some time before crashing with error: 

```ModuleNotFoundError: No module named 'aslprep.smriprep'```

Command:
```singularity run --cleanenv -B /project/def-rmcintos/pjohns/stroke_BIDS:/base aslprep-unstable.simg --participant-label 10450 --skip_bids_validation --scorescrub --fs-license-file $HOME/license/license.txt -vvv /base/NIFTI/ /base/derivatives/ participant```

Full crash log:
```Node: aslprep_wf.single_subject_10450_wf.anat_preproc_wf.anat_norm_wf.registration
Working directory: /home/pjohns/work/aslprep_wf/single_subject_10450_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 454, in run
    cached, updated = self.is_cached()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 342, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 548, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 590, in _get_inputs
    outputs = _load_resultfile(results_fname).outputs
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 293, in load_resultfile
    result = loadpkl(results_file)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 666, in loadpkl
    raise e
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 643, in loadpkl
    unpkl = pickle.loads(pkl_contents)
ModuleNotFoundError: No module named 'aslprep.smriprep'
```

Thank you for your continued help with this!

**Comment by tsalo** [comment]
Are you re-running with an existing working directory?

**Comment by philjohnston** [comment]
Not to my knowledge (I'm not sure how to do that). After pulling the image I just opened a fresh terminal and ran the command above. It ran through quite a few steps before giving me this: 

```
230301-22:12:23,904 nipype.workflow ERROR:
         could not run node: aslprep_wf.single_subject_10450_wf.anat_preproc_wf.anat_norm_wf.registration.a0
230301-22:12:23,910 nipype.workflow INFO:
         crashfile: /base/derivatives/aslprep/sub-10450/log/20230301-215344_f7bee810-4b3a-4dfd-9df1-55f5f462887b/crash-20230301-220926-pjohns-registration.a0-08ab8a41-c759-483f-b9ee-bdf483ed0583.txt 
```

The crash file referenced is the one I included above.

**Comment by tsalo** [comment]
Your working directory appears to be in `/home/pjohns/work`. My guess is that ASLPrep is trying to use the working directory from a previous attempt, in which case it's trying to evaluate steps that won't apply anymore (e.g., I removed the smriprep module from ASLPrep). Can you try using the `--clean-workdir` flag _or_ deleting the contents of `/home/pjohns/work/aslprep_wf/single_subject_10450_wf/`?

**Comment by philjohnston** [comment]
That seems to be the case. I tried with ```--clean-workdir``` and was able to run one subject through the whole pipeline. There were some errors, but I'm assuming they're related to how my inputs were configured. Will follow up if not.

Thanks for your help!

**Comment by tsalo** [comment]
No problem. Best of luck.
