### ISSUE TITLE
Multi-PLD is not supported for GE data

### ISSUE THREAD

**Issue by tsalo** [PennLINC/aslprep#314]
Thanks for your guidance. This error disappeared when I used 3PLD's ASL analysis, but a new errer appeared.

Node: aslprep_wf.single_subject_S0001_wf.asl_preproc_asl.compute_cbf_wf.compute_cbf
Working directory: /work/aslprep_wf/single_subject_S0001_wf/asl_preproc_asl/compute_cbf_wf/compute_cbf

Node inputs:

cbf_only = False
deltam = /work/aslprep_wf/single_subject_S0001_wf/asl_preproc_asl/compute_cbf_wf/extract_deltam/sub-S0001_asl_m0file_brain_mask_cbfdeltam.nii.gz
m0_file = /work/aslprep_wf/single_subject_S0001_wf/asl_preproc_asl/asl_reference_ge_wf/gen_ge_ref/sub-S0001_asl_m0file.nii
m0_scale = 1.0
mask = /work/aslprep_wf/single_subject_S0001_wf/asl_preproc_asl/compute_cbf_wf/refine_mask/sub-S0001_asl_m0file_brain_mask_refinemask.nii.gz
metadata = {'AcquisitionMatrixPE': 8, 'AcquisitionNumber': 1, 'AcquisitionTime': '17:02:21.000000', 'ArterialSpinLabelingType': 'PCASL', 'BackgroundSuppression': True, 'CoilString': '48HAP', 'ConversionSoftware': 'dcm2niix', 'ConversionSoftwareVersion': 'v1.0.20230411', 'DeviceSerialNumber': '0000082427140268', 'EchoTime': 0.012432, 'FlipAngle': 111, 'ImageOrientationPatientDICOM': [1, 0, 0, 0, 1, 0], 'ImageType': ['ORIGINAL', 'PRIMARY', 'OTHER', 'REAL'], 'ImagingFrequency': 127.77, 'InPlanePhaseEncodingDirectionDICOM': 'COL', 'InstitutionName': 'ZJ Hangzhou NO.1 hospital', 'InversionTime': 1, 'LabelingDuration': 1, 'M0Type': 'Included', 'MRAcquisitionType': '3D', 'MagneticFieldStrength': 3, 'Manufacturer': 'GE', 'ManufacturersModelName': 'SIGNA Premier', 'Modality': 'MR', 'NumberOfArms': 8, 'NumberOfPointsPerArm': 512, 'ParallelReductionFactorInPlane': 2, 'PatientPosition': 'HFS', 'PercentPhaseFOV': 100, 'PercentSampling': 100, 'PixelBandwidth': 976.56, 'PostLabelDelay': [1, 2, 3], 'PostLabelingDelay': [1, 2, 3, 0], 'PrescanReuseString': 'RN/s3,Coil/s1', 'ProtocolName': 'research_brain_test_2306', 'PulseSequenceName': 'research/eASL6/easl_PA6', 'ReconMatrixPE': 128, 'RepetitionTime': 10.156, 'RepetitionTimePreparation': 10.156, 'SAR': 1.0431, 'ScanOptions': 'SAT_GEMS\\EDR_GEMS\\SPIRAL_GEMS\\FS', 'ScanningSequence': 'RM', 'SequenceVariant': 'NONE', 'SeriesDescription': 'NOT DIAGNOSTIC: (Raw) EASL_3PLD_1000', 'SeriesNumber': 400, 'ShimSetting': [28, -49, -198], 'SliceThickness': 2, 'SoftwareVersions': '29\\LX\\Product Software Version: RX29.1_R02_2131.a\\Orchestra SDK', 'SpacingBetweenSlices': 2, 'StationName': 'GEHCGEHC', 'VascularCrushing': True, 'timeEncodedMatrixSize': [4, 4]}

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node compute_cbf.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/aslprep/interfaces/cbf.py", line 571, in _run_interface
	    att, mean_cbf = estimate_cbf_pcasl_multipld(
	  File "/usr/local/miniconda/lib/python3.8/site-packages/aslprep/utils/cbf.py", line 700, in estimate_cbf_pcasl_multipld
	    raise ValueError(
	ValueError: Number of PostLabelingDelays (4) does not match number of delta-M volumes (3).

_Originally posted by @Luoyu-Wang in https://github.com/PennLINC/aslprep/issues/310#issuecomment-1613508519_

**Comment by tsalo** [comment]
The gist of this bug is that the M0 volume is not removed from the volume-wise metadata fields, so there's a mismatch in the length of the metadata field (PostLabelingDelay) and the number of volumes in the ASL file.

**Comment by Luoyu-Wang** [comment]
Thanks for your guidance. Has the problem been solved? Also, we are going to rescan a batch of data, because of the time limit, there is a trade-off between Number Of Arms and PLD, one is Number Of Arms=6, 7PLD, the other is Number Of Arms=8, 3PLD, could  you give us some suggestion?

**Comment by tsalo** [comment]
@Luoyu-Wang I haven't figured out the hanging problem, but I think ASLPrep should be able to handle multi-PLD GE data now that I've merged #315. I recommend waiting a couple of hours (until the updated Docker image deploys to DockerHub) and pulling `pennlinc/aslprep:unstable`.

I don't have the expertise to make a recommendation on your protocol, but I've asked around my department to see if any of its ASL experts can weigh in. I would recommend posting your question on NeuroStars to reach a wider audience though.

**Comment by Luoyu-Wang** [comment]
Thanks for your guidance and I would  try out.

**Comment by Luoyu-Wang** [comment]
Hi！Thanks for your guidance. I ran the data successfully, but the CBF results are too high, You said that M0 scan should be scaled by a factor of 32 * the number of averages. In ASLprep,  is this step done automatically? Or do we need to add some extra parameters?
In addition, the result of sub-S0001_space-MNI152NLin2009cAsym_cbf.nii.gz is very strange, could you help us what is the reason?
https://1drv.ms/u/s!AoMxHEmbgddFrpJv-NGglad-qbPNSg?e=D93tm1

**Comment by tsalo** [comment]
Hello @Luoyu-Wang. No, M0 scaling is not done automatically. There is a parameter that allows the user to apply a custom scaling factor (`--m0scale`), but the scaling should optimally be done beforehand, as part of the BIDS conversion. We have some information about this in our documentation: https://aslprep.readthedocs.io/en/latest/usage.html#execution-and-the-bids-format

**Comment by Luoyu-Wang** [comment]
[sub-S0001_cbf.nii.gz](https://github.com/PennLINC/aslprep/files/12157577/sub-S0001_cbf.nii.gz)
Hi，we used the --m0scale and ran the data successful. However, we also found that the strange noise in the results. The noise value is too large(~10^13). Could you help us  what the reason is?
![2023-07-25 140112](https://github.com/PennLINC/aslprep/assets/66916435/2d4175c3-f248-4f18-911b-94e9d0b4e5f8)

**Comment by tsalo** [comment]
@Luoyu-Wang, I'm sorry. I don't know what the issue is, so I contacted someone offline about it, but they haven't gotten back to me. At a glance, perhaps the odd spots are negative CBF estimates, which may be thresholded out.
