### ISSUE TITLE
Mapping CBF images to fsaverage space

### ISSUE THREAD

**Issue by jsbhyyw** [PennLINC/aslprep#418]
Hello!
When I attempted to process data with the command "--output-spaces fsaverage", ASLPrep seems to map the CBF images to the whole brain space which named "sub-Sub001_space-fsaverage_cbf.func.gii", how can I obtain images of hemi-L and hemi-R?
Thank you!

**Comment by tsalo** [comment]
I think that's a bug in how ASLPrep builds output filenames. I will push a fix ASAP. Thanks for reporting this.
