### ISSUE TITLE
CBF quantification

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#61]
Processing finished for a 3d stack-of-spirals pCASL sequence from a SIEMENS scanner, so this is great! However, it's not immediately apparent to me from the "Functional data preprocessing" methods section how the CBF is quantified-- it would be helpful to see the equation used and the values that ended up placed into the equation. I'm also unsure about whether or not the M0 was included in the processing, as the methods make no mention of it. It would be really helpful to see these things so I can validate that I'm BIDS-ifying/setting up my data correctly.

**Comment by a3sha2** [comment]
@caugolm  
we are still  working on the documentation and this part is very important, this will be updated as soon as possible 

there are three ways in which M0 are obtained 
1. aslprep will first check if moscan (`_moscan.nii.gz')  is available for  a particular asl data https://github.com/PennLINC/aslprep/blob/master/aslprep/interfaces/cbf_computation.py#L93

if it is not available, it will go to second option 

2. the second option is to check aslcontext.tsv if the moscan is paired with control and tag https://github.com/PennLINC/aslprep/blob/master/aslprep/interfaces/cbf_computation.py#L97

if no moscan paired with control and tag , then the last option below

3. if both 1 and 2 above are False, then average control is used as  moscan 
https://github.com/PennLINC/aslprep/blob/master/aslprep/interfaces/cbf_computation.py#L119

**Comment by caugolm** [comment]
Thanks! It looks like I was, in fact, naming the m0 wrong in my BIDS heuristic (m0scan.nii.gz instead of moscan.nii.gz)

**Comment by a3sha2** [comment]
@caugolm https://aslprep.readthedocs.io/en/latest/workflows.html

**Comment by HenkMutsaerts** [comment]
I would recommend against this automatic M0 detection, the user should explicitly give an M0 option and a warning or error should be thrown if this was not a workable option. Better if a pipeline doesn't finish than if it finishes with the wrong settings ;)

**Comment by a3sha2** [comment]
Thank you @HenkMutsaerts 
At present, the pipeline  fetches  m0scan  from the json file ('IntendedFor) or from _aslcontext.tsv. 
in the absence of the two options above, we implemented the third option to use average control as m0scan, pls what is your suggestion on this?

In the case where there is no M0scan or precomputed M0 value for `deltam`, the pipeline will exit with error.

**Comment by HenkMutsaerts** [comment]
These options are good, your initial comment suggested that the pipeline would automatically choose between these options, but if it now gives an error if no option is specified, that is good. Using the average control image as pseudo M0 could be automatically taken from the absence of background suppression
