### ISSUE TITLE
PVC method

### ISSUE THREAD

**Issue by caugolm** [PennLINC/aslprep#62]
What partial volume correction method is used? The BASIL documentation mentions the Chappell et al 2011 method, however, my data is single TI so is something closer to the Asllani 2008 method has been implemented?

**Comment by a3sha2** [comment]
The partial volume implemented is the one in BASIL as described in chappell et all 2011 https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/BASIL

it work with both single TI and multiple TI as well. it was implemented directly form  FSL, the code is here https://github.com/PennLINC/aslprep/blob/master/aslprep/interfaces/cbf_computation.py#L613
one of the advantage of BASIL is computation of bolus arrival time with multiple TI  which is also implemented in aslprep  for ordinary cbf computation  
https://github.com/PennLINC/aslprep/blob/master/aslprep/interfaces/cbf_computation.py#L204

**Comment by caugolm** [comment]
Thank you so much for the info!!
