### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by HenkMutsaerts** [PennLINC/aslprep#76]
Why don't you use FastSurfer instead of FreeSurfer, as the latter has far too long computational time for ASL analyses. Also, you could try other better and faster segmentations than FreeSurfer, from the perspective of ASL image analysis.

Why do you use the asymmetrical MNI template?

Great that you have implemented BIDS already! Did you manage to test it with our three test datasets? Did you test our fork of the BIDS validator that has ASL-BIDS included? That would be great!

**Comment by a3sha2** [comment]
thank you @HenkMutsaerts 
I agree, freesurfer take long time to complete but it can be ignore and does not require for cbf computation. Some people may want surface map or do  further processing in surface that is why it was included. We will also look at fastsurfer as well.

On MNI template, we are using the nonlinear symmetric one (ICBM 2009c) from  templateflow (templateflow.org).  we will be glad for your suggestions. 
I test bids validator ( the from Marco Castellaro) and it works. For the datasets that Patricia shared, the nifti images are empty ( for privacy reasons as she wrote  in the email), we will test it and fill the report. 

Please any suggestions is welcome!

**Comment by HenkMutsaerts** [comment]
Good to hear!

Your files suggested that you use an asymmetric template, this is why I asked the question.

Did you also fill in the questionnaire of Sudipto and Jan, for the pipeline inventory? OSIPI task force 1.1?

Did you also test the ASL BIDS validator with some of your own data? That would be great!

**Comment by a3sha2** [comment]
Yes, I have  filled the questionnaire sent by Jan and Sudipto
Yes, I tested the ASL BIDS validators and it is working. I sent reports to Patricia. I also did with our data as well.

**Comment by HenkMutsaerts** [comment]
Great!
