### ISSUE TITLE
[FEATURE] GE scans with only one deltam or  CBF 

### ISSUE THREAD

**Issue by a3sha2** [PennLINC/aslprep#80]
some GE scans have one volume of deltam or  CBF only

- [x]  no reference generation
- [x]  score cant be computed with one volume 
- [x]  BASIL  may not be computed if  the scanner produces CBF/perfusion
- [x]  if there is only CBF and  no deltam or label-tag,  BASIL wont be computed

#79

**Comment by frdarya** [comment]
While trying to run aslprep on data from a GE scanner I ran into some issues:
1) when using deltam and m0 images aslprep seems to run successfully, but the output CBF values are extremely large (in the thousands) and the QEI score extremely low (around 0.01).
2) when using the scanner-computed CBF image aslprep doesn't run at all, with error:
`No single-band-reference found for sub-0001_asl.nii.gz.`
